# Generated by Django 3.2.8 on 2021-10-14 12:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='instance',
            fields=[
                ('url', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('spotify_token', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SongPlayingNow',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('artists', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('duration', models.DurationField(default=None)),
                ('uri', models.CharField(max_length=200)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.instance')),
            ],
        ),
        migrations.CreateModel(
            name='LocalPlaylist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('artists', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('duration', models.DurationField(default=None)),
                ('uri', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('added_mode', models.CharField(max_length=50)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.instance')),
            ],
        ),
    ]
