# Generated by Django 3.2.5 on 2021-11-08 12:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_userinstance_customuser_usersession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_instance_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='instance',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='localplaylist',
            old_name='instance',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='songplayingnow',
            old_name='instance',
            new_name='session',
        ),
    ]
