# Generated by Django 3.2.5 on 2021-11-12 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211108_1247'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LocalPlaylist',
            new_name='Songs',
        ),
    ]
